spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectum?useSSL=false&serverTimezone=UTC
    username: root
    password: 12102021

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false

#logging:
#  level:
    #br.com.cantaruttim: DEBUG

